openapi: 3.2.0
info:
  version: '2014-10-06'
  x-release: v4
  title: 'AWS CodeDeploy #X Amz Target=CodeDeploy…'
  description: CodeDeploy is a deployment service that automates application deployments to Amazon EC2 instances, on-premises instances running in your own facility, serverless Lambda functions, or applications in an Amazon ECS service.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codedeploy
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codedeploy-2014-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: https://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: http://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
- url: https://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeDeploy 20141006.CreateApplication'
paths:
  /#X-Amz-Target=CodeDeploy_20141006.CreateApplication:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateApplication
      description: Creates an application.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateApplicationOutput'
              examples:
                CreateApplication200Example:
                  summary: Default CreateApplication 200 response
                  x-microcks-default: true
                  value:
                    applicationId: '500123'
        '480':
          description: ApplicationNameRequiredException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationNameRequiredException'
              examples:
                CreateApplication480Example:
                  summary: Default CreateApplication 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InvalidApplicationNameException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidApplicationNameException'
              examples:
                CreateApplication481Example:
                  summary: Default CreateApplication 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ApplicationAlreadyExistsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationAlreadyExistsException'
              examples:
                CreateApplication482Example:
                  summary: Default CreateApplication 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ApplicationLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationLimitExceededException'
              examples:
                CreateApplication483Example:
                  summary: Default CreateApplication 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: InvalidComputePlatformException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidComputePlatformException'
              examples:
                CreateApplication484Example:
                  summary: Default CreateApplication 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: InvalidTagsToAddException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidTagsToAddException'
              examples:
                CreateApplication485Example:
                  summary: Default CreateApplication 485 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApplicationInput'
            examples:
              CreateApplicationRequestExample:
                summary: Default CreateApplication request
                x-microcks-default: true
                value:
                  applicationName: example-resource
                  computePlatform: example-value
                  tags: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeDeploy_20141006.CreateApplication
      summary: Amazon CodeDeploy Create Application
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeDeploy 20141006.CreateApplication'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  schemas:
    CreateApplicationInput:
      type: object
      required:
      - applicationName
      title: CreateApplicationInput
      properties:
        applicationName:
          allOf:
          - $ref: '#/components/schemas/ApplicationName'
          - description: The name of the application. This name must be unique with the applicable IAM or Amazon Web Services account.
        computePlatform:
          allOf:
          - $ref: '#/components/schemas/ComputePlatform'
          - description: ' The destination platform type for the deployment (<code>Lambda</code>, <code>Server</code>, or <code>ECS</code>).'
        tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: ' The metadata that you apply to CodeDeploy applications to help you organize and categorize them. Each tag consists of a key and an optional value, both of which you define. '
      description: Represents the input of a <code>CreateApplication</code> operation.
    ApplicationNameRequiredException: {}
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    InvalidTagsToAddException: {}
    InvalidApplicationNameException: {}
    Key:
      type: string
    ApplicationLimitExceededException: {}
    Value:
      type: string
    Tag:
      type: object
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/Key'
          - description: The tag's key.
        Value:
          allOf:
          - $ref: '#/components/schemas/Value'
          - description: The tag's value.
      description: Information about a tag.
    ApplicationId:
      type: string
    ApplicationName:
      type: string
      minLength: 1
      maxLength: 100
    InvalidComputePlatformException: {}
    CreateApplicationOutput:
      type: object
      properties:
        applicationId:
          allOf:
          - $ref: '#/components/schemas/ApplicationId'
          - description: A unique application ID.
      description: Represents the output of a <code>CreateApplication</code> operation.
    ApplicationAlreadyExistsException: {}
    ComputePlatform:
      type: string
      enum:
      - Server
      - Lambda
      - ECS
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codedeploy/
x-hasEquivalentPaths: true
