openapi: 3.2.0
info:
  version: '2014-10-06'
  x-release: v4
  title: 'AWS CodeDeploy #X Amz Target=CodeDeploy…'
  description: CodeDeploy is a deployment service that automates application deployments to Amazon EC2 instances, on-premises instances running in your own facility, serverless Lambda functions, or applications in an Amazon ECS service.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codedeploy
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codedeploy-2014-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: https://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: http://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
- url: https://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeDeploy 20141006.ListDeploymentInstances'
paths:
  /#X-Amz-Target=CodeDeploy_20141006.ListDeploymentInstances:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      deprecated: true
      operationId: ListDeploymentInstances
      description: 'The newer BatchGetDeploymentTargets should be used instead because it works with all compute types. ListDeploymentInstances throws an exception if it is used with a compute platform other than EC2/On-premises or Lambda.


        Lists the instance for a deployment associated with the IAM user or Amazon Web Services account.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDeploymentInstancesOutput'
              examples:
                ListDeploymentInstances200Example:
                  summary: Default ListDeploymentInstances 200 response
                  x-microcks-default: true
                  value:
                    instancesList: example-value
                    nextToken: example-value
        '480':
          description: DeploymentIdRequiredException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentIdRequiredException'
              examples:
                ListDeploymentInstances480Example:
                  summary: Default ListDeploymentInstances 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: DeploymentDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentDoesNotExistException'
              examples:
                ListDeploymentInstances481Example:
                  summary: Default ListDeploymentInstances 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: DeploymentNotStartedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentNotStartedException'
              examples:
                ListDeploymentInstances482Example:
                  summary: Default ListDeploymentInstances 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: InvalidNextTokenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidNextTokenException'
              examples:
                ListDeploymentInstances483Example:
                  summary: Default ListDeploymentInstances 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: InvalidDeploymentIdException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidDeploymentIdException'
              examples:
                ListDeploymentInstances484Example:
                  summary: Default ListDeploymentInstances 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: InvalidInstanceStatusException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInstanceStatusException'
              examples:
                ListDeploymentInstances485Example:
                  summary: Default ListDeploymentInstances 485 response
                  x-microcks-default: true
                  value: example-value
        '486':
          description: InvalidInstanceTypeException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInstanceTypeException'
              examples:
                ListDeploymentInstances486Example:
                  summary: Default ListDeploymentInstances 486 response
                  x-microcks-default: true
                  value: example-value
        '487':
          description: InvalidDeploymentInstanceTypeException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidDeploymentInstanceTypeException'
              examples:
                ListDeploymentInstances487Example:
                  summary: Default ListDeploymentInstances 487 response
                  x-microcks-default: true
                  value: example-value
        '488':
          description: InvalidTargetFilterNameException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidTargetFilterNameException'
              examples:
                ListDeploymentInstances488Example:
                  summary: Default ListDeploymentInstances 488 response
                  x-microcks-default: true
                  value: example-value
        '489':
          description: InvalidComputePlatformException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidComputePlatformException'
              examples:
                ListDeploymentInstances489Example:
                  summary: Default ListDeploymentInstances 489 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListDeploymentInstancesInput'
            examples:
              ListDeploymentInstancesRequestExample:
                summary: Default ListDeploymentInstances request
                x-microcks-default: true
                value:
                  deploymentId: '500123'
                  nextToken: example-value
                  instanceStatusFilter: ACTIVE
                  instanceTypeFilter: STANDARD
      parameters:
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeDeploy_20141006.ListDeploymentInstances
      summary: Amazon CodeDeploy List Deployment Instances
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeDeploy 20141006.ListDeploymentInstances'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    InvalidDeploymentInstanceTypeException: {}
    ListDeploymentInstancesOutput:
      type: object
      properties:
        instancesList:
          allOf:
          - $ref: '#/components/schemas/InstancesList'
          - description: A list of instance IDs.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: If a large amount of information is returned, an identifier is also returned. It can be used in a subsequent list deployment instances call to return the next set of deployment instances in the list.
      description: Represents the output of a <code>ListDeploymentInstances</code> operation.
    InvalidInstanceStatusException: {}
    DeploymentDoesNotExistException: {}
    NextToken:
      type: string
    InstanceType:
      type: string
      enum:
      - Blue
      - Green
    ListDeploymentInstancesInput:
      type: object
      required:
      - deploymentId
      title: ListDeploymentInstancesInput
      properties:
        deploymentId:
          allOf:
          - $ref: '#/components/schemas/DeploymentId'
          - description: ' The unique ID of a deployment. '
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: An identifier returned from the previous list deployment instances call. It can be used to return the next set of deployment instances in the list.
        instanceStatusFilter:
          allOf:
          - $ref: '#/components/schemas/InstanceStatusList'
          - description: '<p>A subset of instances to list by status:</p> <ul> <li> <p> <code>Pending</code>: Include those instances with pending deployments.</p> </li> <li> <p> <code>InProgress</code>: Include those instances where deployments are still in progress.</p> </li> <li> <p> <code>Succeeded</code>: Include those instances with successful deployments.</p> </li> <li> <p> <code>Failed</code>: Include those instances with failed deployments.</p> </li> <li> <p> <code>Skipped</code>: Include those instances with skipped deployments.</p> </li> <li> <p> <code>Unknown</code>: Include those instances with deployments in an unknown state.</p> </li> </ul>'
        instanceTypeFilter:
          allOf:
          - $ref: '#/components/schemas/InstanceTypeList'
          - description: The set of instances in a blue/green deployment, either those in the original environment ("BLUE") or those in the replacement environment ("GREEN"), for which you want to view instance information.
      description: ' Represents the input of a <code>ListDeploymentInstances</code> operation. '
    DeploymentNotStartedException: {}
    InstanceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceType'
    InstancesList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceId'
    InvalidDeploymentIdException: {}
    InvalidInstanceTypeException: {}
    InstanceStatusList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceStatus'
    InvalidTargetFilterNameException: {}
    InvalidComputePlatformException: {}
    InstanceId:
      type: string
    InstanceStatus:
      type: string
      deprecated: true
      enum:
      - Pending
      - InProgress
      - Succeeded
      - Failed
      - Skipped
      - Unknown
      - Ready
      description: InstanceStatus is deprecated, use TargetStatus instead.
    InvalidNextTokenException: {}
    DeploymentId:
      type: string
    DeploymentIdRequiredException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codedeploy/
x-hasEquivalentPaths: true
