openapi: 3.2.0
info:
  version: '2014-10-06'
  x-release: v4
  title: 'AWS CodeDeploy #X Amz Target=CodeDeploy…'
  description: CodeDeploy is a deployment service that automates application deployments to Amazon EC2 instances, on-premises instances running in your own facility, serverless Lambda functions, or applications in an Amazon ECS service.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codedeploy
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codedeploy-2014-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: https://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: http://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
- url: https://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeDeploy 20141006.UntagResource'
paths:
  /#X-Amz-Target=CodeDeploy_20141006.UntagResource:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: UntagResource
      description: Disassociates a resource from a list of tags. The resource is identified by the ResourceArn input parameter. The tags are identified by the list of keys in the TagKeys input parameter.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UntagResourceOutput'
              examples:
                UntagResource200Example:
                  summary: Default UntagResource 200 response
                  x-microcks-default: true
                  value: {}
        '480':
          description: ResourceArnRequiredException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceArnRequiredException'
              examples:
                UntagResource480Example:
                  summary: Default UntagResource 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ApplicationDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationDoesNotExistException'
              examples:
                UntagResource481Example:
                  summary: Default UntagResource 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: DeploymentGroupDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentGroupDoesNotExistException'
              examples:
                UntagResource482Example:
                  summary: Default UntagResource 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: DeploymentConfigDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentConfigDoesNotExistException'
              examples:
                UntagResource483Example:
                  summary: Default UntagResource 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: TagRequiredException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagRequiredException'
              examples:
                UntagResource484Example:
                  summary: Default UntagResource 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: InvalidTagsToAddException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidTagsToAddException'
              examples:
                UntagResource485Example:
                  summary: Default UntagResource 485 response
                  x-microcks-default: true
                  value: example-value
        '486':
          description: ArnNotSupportedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArnNotSupportedException'
              examples:
                UntagResource486Example:
                  summary: Default UntagResource 486 response
                  x-microcks-default: true
                  value: example-value
        '487':
          description: InvalidArnException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArnException'
              examples:
                UntagResource487Example:
                  summary: Default UntagResource 487 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UntagResourceInput'
            examples:
              UntagResourceRequestExample:
                summary: Default UntagResource request
                x-microcks-default: true
                value:
                  ResourceArn: arn:aws:service:us-east-1:123456789012:resource/example
                  TagKeys: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeDeploy_20141006.UntagResource
      summary: Amazon CodeDeploy Untag Resource
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeDeploy 20141006.UntagResource'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  schemas:
    UntagResourceInput:
      type: object
      required:
      - ResourceArn
      - TagKeys
      title: UntagResourceInput
      properties:
        ResourceArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The Amazon Resource Name (ARN) that specifies from which resource to disassociate the tags with the keys in the <code>TagKeys</code> input parameter. '
        TagKeys:
          allOf:
          - $ref: '#/components/schemas/TagKeyList'
          - description: ' A list of keys of <code>Tag</code> objects. The <code>Tag</code> objects identified by the keys are disassociated from the resource specified by the <code>ResourceArn</code> input parameter. '
    InvalidTagsToAddException: {}
    Key:
      type: string
    DeploymentConfigDoesNotExistException: {}
    Arn:
      type: string
      minLength: 1
      maxLength: 1011
    InvalidArnException: {}
    ArnNotSupportedException: {}
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/Key'
    ApplicationDoesNotExistException: {}
    DeploymentGroupDoesNotExistException: {}
    UntagResourceOutput:
      type: object
      properties: {}
    TagRequiredException: {}
    ResourceArnRequiredException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codedeploy/
x-hasEquivalentPaths: true
