openapi: 3.2.0
info:
  version: '2014-10-06'
  x-release: v4
  title: 'AWS CodeDeploy #X Amz Target=CodeDeploy…'
  description: CodeDeploy is a deployment service that automates application deployments to Amazon EC2 instances, on-premises instances running in your own facility, serverless Lambda functions, or applications in an Amazon ECS service.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codedeploy
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codedeploy-2014-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: https://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: http://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
- url: https://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeDeploy 20141006.PutLifecycleEventHookExecutionStatus'
paths:
  /#X-Amz-Target=CodeDeploy_20141006.PutLifecycleEventHookExecutionStatus:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutLifecycleEventHookExecutionStatus
      description: Sets the result of a Lambda validation function. The function validates lifecycle hooks during a deployment that uses the Lambda or Amazon ECS compute platform. For Lambda deployments, the available lifecycle hooks are BeforeAllowTraffic and AfterAllowTraffic. For Amazon ECS deployments, the available lifecycle hooks are BeforeInstall, AfterInstall, AfterAllowTestTraffic, BeforeAllowTraffic, and AfterAllowTraffic. Lambda validation functions return Succeeded or Failed. For more information, see AppSpec 'hooks' Section for an Lambda Deployment and AppSpec 'hooks' Section for an Amazon ECS Deployment.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutLifecycleEventHookExecutionStatusOutput'
              examples:
                PutLifecycleEventHookExecutionStatus200Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 200 response
                  x-microcks-default: true
                  value:
                    lifecycleEventHookExecutionId: '500123'
        '480':
          description: InvalidLifecycleEventHookExecutionStatusException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidLifecycleEventHookExecutionStatusException'
              examples:
                PutLifecycleEventHookExecutionStatus480Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 480 response
                  x-microcks-default: true
                  value: ACTIVE
        '481':
          description: InvalidLifecycleEventHookExecutionIdException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidLifecycleEventHookExecutionIdException'
              examples:
                PutLifecycleEventHookExecutionStatus481Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 481 response
                  x-microcks-default: true
                  value: ACTIVE
        '482':
          description: LifecycleEventAlreadyCompletedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LifecycleEventAlreadyCompletedException'
              examples:
                PutLifecycleEventHookExecutionStatus482Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 482 response
                  x-microcks-default: true
                  value: ACTIVE
        '483':
          description: DeploymentIdRequiredException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentIdRequiredException'
              examples:
                PutLifecycleEventHookExecutionStatus483Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 483 response
                  x-microcks-default: true
                  value: ACTIVE
        '484':
          description: DeploymentDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentDoesNotExistException'
              examples:
                PutLifecycleEventHookExecutionStatus484Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 484 response
                  x-microcks-default: true
                  value: ACTIVE
        '485':
          description: InvalidDeploymentIdException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidDeploymentIdException'
              examples:
                PutLifecycleEventHookExecutionStatus485Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 485 response
                  x-microcks-default: true
                  value: ACTIVE
        '486':
          description: UnsupportedActionForDeploymentTypeException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedActionForDeploymentTypeException'
              examples:
                PutLifecycleEventHookExecutionStatus486Example:
                  summary: Default PutLifecycleEventHookExecutionStatus 486 response
                  x-microcks-default: true
                  value: ACTIVE
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutLifecycleEventHookExecutionStatusInput'
            examples:
              PutLifecycleEventHookExecutionStatusRequestExample:
                summary: Default PutLifecycleEventHookExecutionStatus request
                x-microcks-default: true
                value:
                  deploymentId: '500123'
                  lifecycleEventHookExecutionId: '500123'
                  status: ACTIVE
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeDeploy_20141006.PutLifecycleEventHookExecutionStatus
      summary: Amazon CodeDeploy Put Lifecycle Event Hook Execution Status
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeDeploy 20141006.PutLifecycleEventHookExecutionStatus'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    PutLifecycleEventHookExecutionStatusInput:
      type: object
      title: PutLifecycleEventHookExecutionStatusInput
      properties:
        deploymentId:
          allOf:
          - $ref: '#/components/schemas/DeploymentId'
          - description: ' The unique ID of a deployment. Pass this ID to a Lambda function that validates a deployment lifecycle event. '
        lifecycleEventHookExecutionId:
          allOf:
          - $ref: '#/components/schemas/LifecycleEventHookExecutionId'
          - description: ' The execution ID of a deployment''s lifecycle hook. A deployment lifecycle hook is specified in the <code>hooks</code> section of the AppSpec file. '
        status:
          allOf:
          - $ref: '#/components/schemas/LifecycleEventStatus'
          - description: The result of a Lambda function that validates a deployment lifecycle event. The values listed in <b>Valid Values</b> are valid for lifecycle statuses in general; however, only <code>Succeeded</code> and <code>Failed</code> can be passed successfully in your API call.
    UnsupportedActionForDeploymentTypeException: {}
    InvalidLifecycleEventHookExecutionStatusException: {}
    DeploymentDoesNotExistException: {}
    LifecycleEventAlreadyCompletedException: {}
    InvalidLifecycleEventHookExecutionIdException: {}
    InvalidDeploymentIdException: {}
    LifecycleEventStatus:
      type: string
      enum:
      - Pending
      - InProgress
      - Succeeded
      - Failed
      - Skipped
      - Unknown
    PutLifecycleEventHookExecutionStatusOutput:
      type: object
      properties:
        lifecycleEventHookExecutionId:
          allOf:
          - $ref: '#/components/schemas/LifecycleEventHookExecutionId'
          - description: The execution ID of the lifecycle event hook. A hook is specified in the <code>hooks</code> section of the deployment's AppSpec file.
    LifecycleEventHookExecutionId:
      type: string
    DeploymentId:
      type: string
    DeploymentIdRequiredException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codedeploy/
x-hasEquivalentPaths: true
