openapi: 3.2.0
info:
  version: '2014-10-06'
  x-release: v4
  title: 'AWS CodeDeploy #X Amz Target=CodeDeploy…'
  description: CodeDeploy is a deployment service that automates application deployments to Amazon EC2 instances, on-premises instances running in your own facility, serverless Lambda functions, or applications in an Amazon ECS service.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codedeploy
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codedeploy-2014-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: https://codedeploy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeDeploy multi-region endpoint
- url: http://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
- url: https://codedeploy.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeDeploy endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeDeploy 20141006.DeleteGitHubAccountToken'
paths:
  /#X-Amz-Target=CodeDeploy_20141006.DeleteGitHubAccountToken:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DeleteGitHubAccountToken
      description: Deletes a GitHub account connection.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteGitHubAccountTokenOutput'
              examples:
                DeleteGitHubAccountToken200Example:
                  summary: Default DeleteGitHubAccountToken 200 response
                  x-microcks-default: true
                  value:
                    tokenName: example-resource
        '480':
          description: GitHubAccountTokenNameRequiredException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GitHubAccountTokenNameRequiredException'
              examples:
                DeleteGitHubAccountToken480Example:
                  summary: Default DeleteGitHubAccountToken 480 response
                  x-microcks-default: true
                  value: '123456789012'
        '481':
          description: GitHubAccountTokenDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GitHubAccountTokenDoesNotExistException'
              examples:
                DeleteGitHubAccountToken481Example:
                  summary: Default DeleteGitHubAccountToken 481 response
                  x-microcks-default: true
                  value: '123456789012'
        '482':
          description: InvalidGitHubAccountTokenNameException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGitHubAccountTokenNameException'
              examples:
                DeleteGitHubAccountToken482Example:
                  summary: Default DeleteGitHubAccountToken 482 response
                  x-microcks-default: true
                  value: '123456789012'
        '483':
          description: ResourceValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceValidationException'
              examples:
                DeleteGitHubAccountToken483Example:
                  summary: Default DeleteGitHubAccountToken 483 response
                  x-microcks-default: true
                  value: '123456789012'
        '484':
          description: OperationNotSupportedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationNotSupportedException'
              examples:
                DeleteGitHubAccountToken484Example:
                  summary: Default DeleteGitHubAccountToken 484 response
                  x-microcks-default: true
                  value: '123456789012'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteGitHubAccountTokenInput'
            examples:
              DeleteGitHubAccountTokenRequestExample:
                summary: Default DeleteGitHubAccountToken request
                x-microcks-default: true
                value:
                  tokenName: example-resource
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeDeploy_20141006.DeleteGitHubAccountToken
      summary: Amazon CodeDeploy Delete Git Hub Account Token
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeDeploy 20141006.DeleteGitHubAccountToken'
components:
  schemas:
    OperationNotSupportedException: {}
    GitHubAccountTokenDoesNotExistException: {}
    DeleteGitHubAccountTokenInput:
      type: object
      title: DeleteGitHubAccountTokenInput
      properties:
        tokenName:
          allOf:
          - $ref: '#/components/schemas/GitHubAccountTokenName'
          - description: The name of the GitHub account connection to delete.
      description: Represents the input of a <code>DeleteGitHubAccount</code> operation.
    InvalidGitHubAccountTokenNameException: {}
    GitHubAccountTokenNameRequiredException: {}
    DeleteGitHubAccountTokenOutput:
      type: object
      properties:
        tokenName:
          allOf:
          - $ref: '#/components/schemas/GitHubAccountTokenName'
          - description: The name of the GitHub account connection that was deleted.
      description: Represents the output of a <code>DeleteGitHubAccountToken</code> operation.
    GitHubAccountTokenName:
      type: string
    ResourceValidationException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codedeploy/
x-hasEquivalentPaths: true
